In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title: Python program compare two arrays using numpy.
'''

In [1]:
import numpy as np

In [2]:
arrA=np.array([1,2])
arrB=np.array([4,5])

In [4]:
print("arrA>arrB")
np.greater(arrA,arrB)

arrA>arrB


array([False, False])

In [6]:
print("arrA<arrB")
np.less(arrA,arrB)

arrA<arrB


array([ True,  True])

In [7]:
print("arrA>=arrB")
np.greater_equal(arrA,arrB)

arrA>=arrB


array([False, False])

In [8]:
print("arrA<=arrB")
np.less_equal(arrA,arrB)

arrA<=arrB


array([ True,  True])