In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title:Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]
'''

In [1]:
import numpy as np

In [4]:
arr1_2D=np.arange(0,11,2).reshape(2,3)
print(arr1_2D)

[[ 0  2  4]
 [ 6  8 10]]


In [6]:
arr2_2D=np.arange(0,18,3).reshape(2,3)
print(arr2_2D)

[[ 0  3  6]
 [ 9 12 15]]


In [9]:
arrConcatenate=np.concatenate((arr1_2D,arr2_2D),axis=1)
print(arrConcatenate)

[[ 0  2  4  0  3  6]
 [ 6  8 10  9 12 15]]
