In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title:Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[16 16 59 55]
 [55 32 93 86]
 [93 83 11 57]]
New array elements:
[[ 48  48 177 165]
 [165  96 279 258]
 [279 249  33 171]]
'''

In [5]:
import numpy as np
from numpy import random

In [11]:
arrInt=random.randint(100,size=(3,4))
print(arrInt.dtype)
print(arrInt)

int32
[[16 16 59 55]
 [55 32 93 86]
 [93 83 11 57]]


In [12]:
arrInt=arrInt*3
print(arrInt)

[[ 48  48 177 165]
 [165  96 279 258]
 [279 249  33 171]]
