In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title:Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]
'''

In [2]:
import numpy as np

In [5]:
arr1=np.array([ 1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
np.set_printoptions(precision=3,suppress=True)
print(arr1)

[   0.       1.6   1200.       0.235]
