In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title:Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]
'''

In [1]:
import numpy as np

In [3]:
arr1=np.arange(10,70,10).reshape(2,3)
arr2=np.arange(100,300,100).reshape(2,1)

In [5]:
np.append(arr1,arr2,axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])