In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title:Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]
'''

In [2]:
import numpy as np

In [5]:
arr1=np.arange(10,110,10)

In [4]:
np.delete(arr1,[0,3,4])

array([ 20,  30,  60,  70,  80,  90, 100])