In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title: Create 3x3 matrix from 2 to 10.
'''

In [1]:
import numpy as np

In [13]:
matrix=np.arange(2,11)

In [14]:
arrMatrix=matrix.reshape(3,3)

In [15]:
print(arrMatrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
