In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title: Create a 2d array with 1 on the border and 0 inside.
'''

In [1]:
import numpy as np

In [21]:
arr=np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
