In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title: Create a 2d array with 0 on the border and 1 inside.
'''

In [1]:
import numpy as np

In [6]:
arrMatrix=np.ones((3,3))
print(arrMatrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arrMatrix=np.pad(arrMatrix,pad_width=1,mode='constant',constant_values=0)

In [12]:
print(arrMatrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
