In [ ]:
'''
@Author:Shivam Mathur
@Date:2021-07-12
@Last Modified by:Shivam Mathur
@Last Modified time:2021-07-12
@Title: Convert list and tuple to array.
'''

In [1]:
import numpy as np

In [9]:
originalList=[1,2,3,4,4,6]
originalTuple=((4,5,6),(7,8,9))

In [10]:
listArray=np.asarray(originalList)
tupleArray=np.asarray(originalTuple)

In [11]:
print(listArray)
print(tupleArray)

[1 2 3 4 4 6]
[[4 5 6]
 [7 8 9]]
